-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-08-13 21:48:12 AEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE citizenship (
    from_date            DATE NOT NULL,
    thru_date            DATE,
    country_country_code CHAR(2 CHAR) NOT NULL,
    pers_pers_id         NUMBER NOT NULL
);

ALTER TABLE citizenship ADD CONSTRAINT citzn_pk PRIMARY KEY ( from_date );

CREATE TABLE country (
    country_code CHAR(2 CHAR) NOT NULL,
    country_name VARCHAR2(128)
);

COMMENT ON COLUMN country.country_code IS
    'ISO Country code';

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_code );

CREATE TABLE gender_type (
    gender_type_id CHAR(2 CHAR) NOT NULL,
    description    VARCHAR2(1024 CHAR) NOT NULL
);

ALTER TABLE gender_type ADD CONSTRAINT gender_typ_pk PRIMARY KEY ( gender_type_id );

CREATE TABLE marital_status (
    from_date         DATE NOT NULL,
    thru_date         DATE,
    martl_stat_typ_id NUMBER NOT NULL,
    pers_pers_id      NUMBER NOT NULL
);

ALTER TABLE marital_status ADD CONSTRAINT martl_stat_pk PRIMARY KEY ( from_date );

CREATE TABLE marital_status_type (
    marital_status_type_id NUMBER NOT NULL,
    description            VARCHAR2(1024 CHAR) NOT NULL
);

ALTER TABLE marital_status_type ADD CONSTRAINT martl_stat_typ_pk PRIMARY KEY ( marital_status_type_id );

CREATE TABLE passport (
    passport_id     NUMBER NOT NULL,
    passport_num    NUMBER NOT NULL,
    issue_date      DATE NOT NULL,
    expiry_date     DATE NOT NULL,
    citzn_from_date DATE NOT NULL
);

ALTER TABLE passport ADD CONSTRAINT passport_pk PRIMARY KEY ( passport_id );

CREATE TABLE person (
    birth_date                  DATE,
    mothers_maiden_name         VARCHAR2(512 CHAR),
    social_security_no          VARCHAR2(32 CHAR),
    total_years_work_experience SMALLINT,
    "Comment"                   VARCHAR2(512 CHAR),
    gender_typ_gender_typ_id    CHAR(2 CHAR) NOT NULL,
    pers_id                     NUMBER NOT NULL
);

ALTER TABLE person ADD CONSTRAINT pers_pk PRIMARY KEY ( pers_id );

CREATE TABLE person_name (
    name_seq_id               NUMBER NOT NULL,
    from_date                 DATE NOT NULL,
    thru_date                 DATE,
    name                      VARCHAR2(512 CHAR) NOT NULL,
    pers_name_typ_pers_typ_id NUMBER NOT NULL,
    pers_pers_id              NUMBER NOT NULL
);

ALTER TABLE person_name ADD CONSTRAINT pers_name_pk PRIMARY KEY ( name_seq_id );

CREATE TABLE person_name_type (
    person_type_id NUMBER NOT NULL,
    description    VARCHAR2(1024 CHAR) NOT NULL
);

ALTER TABLE person_name_type ADD CONSTRAINT pers_name_typ_pk PRIMARY KEY ( person_type_id );

CREATE TABLE physical_characteristic (
    from_date                 DATE NOT NULL,
    thru_date                 DATE,
    phys_char_typ_char_typ_id NUMBER NOT NULL,
    pers_pers_id              NUMBER NOT NULL
);

CREATE TABLE physical_characteristic_type (
    characteristic_type_id NUMBER NOT NULL,
    description            VARCHAR2(1024 CHAR) NOT NULL
);

ALTER TABLE physical_characteristic_type ADD CONSTRAINT phys_char_typ_pk PRIMARY KEY ( characteristic_type_id );

ALTER TABLE citizenship
    ADD CONSTRAINT citzn_country_fk FOREIGN KEY ( country_country_code )
        REFERENCES country ( country_code );

ALTER TABLE citizenship
    ADD CONSTRAINT citzn_pers_fk FOREIGN KEY ( pers_pers_id )
        REFERENCES person ( pers_id );

ALTER TABLE marital_status
    ADD CONSTRAINT martl_stat_martl_stat_typ_fk FOREIGN KEY ( martl_stat_typ_id )
        REFERENCES marital_status_type ( marital_status_type_id );

ALTER TABLE marital_status
    ADD CONSTRAINT martl_stat_pers_fk FOREIGN KEY ( pers_pers_id )
        REFERENCES person ( pers_id );

ALTER TABLE passport
    ADD CONSTRAINT passport_citzn_fk FOREIGN KEY ( citzn_from_date )
        REFERENCES citizenship ( from_date );

ALTER TABLE person
    ADD CONSTRAINT pers_gender_typ_fk FOREIGN KEY ( gender_typ_gender_typ_id )
        REFERENCES gender_type ( gender_type_id );

ALTER TABLE person_name
    ADD CONSTRAINT pers_name_pers_fk FOREIGN KEY ( pers_pers_id )
        REFERENCES person ( pers_id );

ALTER TABLE person_name
    ADD CONSTRAINT pers_name_pers_name_typ_fk FOREIGN KEY ( pers_name_typ_pers_typ_id )
        REFERENCES person_name_type ( person_type_id );

ALTER TABLE physical_characteristic
    ADD CONSTRAINT phys_char_pers_fk FOREIGN KEY ( pers_pers_id )
        REFERENCES person ( pers_id );

ALTER TABLE physical_characteristic
    ADD CONSTRAINT phys_char_phys_char_typ_fk FOREIGN KEY ( phys_char_typ_char_typ_id )
        REFERENCES physical_characteristic_type ( characteristic_type_id );

CREATE SEQUENCE person_pers_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER person_pers_id_trg BEFORE
    INSERT ON person
    FOR EACH ROW
    WHEN ( new.pers_id IS NULL )
BEGIN
    :new.pers_id := person_pers_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
