-- drop table "URM"."LEGAL_ORGANIZATION"  PURGE; -- dropped previously
drop table "URM"."INFORMAL_ORGANIZATION"  PURGE;
drop table "URM"."ORGANIZATION"  PURGE;
drop table "URM"."ORGANIZATION_ROLLUP" PURGE;
rename "ORGANIZATION_CLASSIFICATION" to "ORGANISATION_CLASSIFICATION";
rename "ORGANIZATION_CONTACT_RELATIONSHIP" to "ORGANISATION_CONTACT_RELATIONSHIP";

